name = "todoapp_localstorage"
version = "1.0.0"

target = "javascript"

description = "Simple todolist application with storage in LocalStorage written in Gleam with the Lustre framework."
licences = ["MIT"]
repository = {type = "github", user = "emarifer", repo = "todoapp_localstorage"}

links = [
  {title = "Repositories", href = "https://github.com/emarifer?tab=repositories"},
]

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
formal = ">= 3.0.0 and < 4.0.0"
gleam_json = ">= 3.1.0 and < 4.0.0"
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
lustre = ">= 5.4.0 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
lustre_dev_tools = ">= 2.3.1 and < 3.0.0"

[tools.lustre.html]
links = [
  {rel = "icon", href = "/images/logo.png", type = "image/png"},
  {rel = "preconnect", href = "https://fonts.googleapis.com"},
  {rel = "preconnect", href = "https://fonts.gstatic.com", crossorigin = ""},
  {rel = "stylesheet", href = "https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"},
]
meta = [{name = "google", content = "notranslate"}]
title = "Todoapp Lustre"
